export interface GameDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: "cyan" | "green" | "purple" | "pink" | "yellow" | "red";
  controls: string;
}

export const GAMES: GameDefinition[] = [
  {
    id: "snake",
    name: "Snake",
    icon: "🐍",
    description: "Eat food, grow longer. Don't hit walls or yourself!",
    color: "green",
    controls: "Arrow keys / WASD",
  },
  {
    id: "tetris",
    name: "Tetris",
    icon: "🟦",
    description: "Stack falling blocks and clear lines to score big!",
    color: "cyan",
    controls: "Arrow keys + Up to rotate",
  },
  {
    id: "2048",
    name: "2048",
    icon: "🔢",
    description: "Merge tiles to reach 2048. Can you go further?",
    color: "yellow",
    controls: "Arrow keys / swipe",
  },
  {
    id: "flappy",
    name: "Flappy Bird",
    icon: "🐦",
    description: "Tap or press space to flap through the pipes!",
    color: "green",
    controls: "Click / Space bar",
  },
  {
    id: "memory",
    name: "Memory Match",
    icon: "🃏",
    description: "Match all pairs with the fewest moves possible!",
    color: "purple",
    controls: "Click to flip cards",
  },
  {
    id: "minesweeper",
    name: "Minesweeper",
    icon: "💣",
    description: "Reveal all safe cells without hitting a mine!",
    color: "pink",
    controls: "Left click reveal, Right click flag",
  },
  {
    id: "breakout",
    name: "Breakout",
    icon: "🧱",
    description: "Bounce the ball to break all the bricks!",
    color: "cyan",
    controls: "Mouse / touch to move paddle",
  },
  {
    id: "whackmole",
    name: "Whack-a-Mole",
    icon: "🦔",
    description: "Whack as many moles as you can in 30 seconds!",
    color: "yellow",
    controls: "Click the moles",
  },
  {
    id: "pacman",
    name: "Pac-Man",
    icon: "👾",
    description: "Eat all the dots, avoid ghosts, use power pellets to turn the tables!",
    color: "yellow",
    controls: "Arrow keys / WASD",
  },
  {
    id: "spaceinvaders",
    name: "Space Invaders",
    icon: "👽",
    description: "Defend Earth from waves of alien invaders!",
    color: "green",
    controls: "Arrow keys + Space to shoot",
  },
  {
    id: "asteroids",
    name: "Asteroids",
    icon: "🚀",
    description: "Blast asteroids into pieces before they destroy your ship!",
    color: "cyan",
    controls: "A/D rotate, W thrust, Space shoot",
  },
  {
    id: "pong",
    name: "Pong",
    icon: "🏓",
    description: "Classic Pong! First to 7 points wins the match.",
    color: "cyan",
    controls: "Mouse / Arrow keys / Touch",
  },
  {
    id: "frogger",
    name: "Frogger",
    icon: "🐸",
    description: "Hop across lanes of traffic and logs to reach safety!",
    color: "green",
    controls: "Arrow keys / D-pad",
  },
  {
    id: "bubbleshooter",
    name: "Bubble Shooter",
    icon: "🫧",
    description: "Aim and shoot bubbles to pop groups of 3 or more!",
    color: "purple",
    controls: "Mouse to aim, click to shoot",
  },
  {
    id: "connectfour",
    name: "Connect Four",
    icon: "🔴",
    description: "Drop discs and connect 4 in a row to beat the AI!",
    color: "red",
    controls: "Click column to drop disc",
  },
  {
    id: "simonsays",
    name: "Simon Says",
    icon: "🟢",
    description: "Watch and repeat the growing color sequence!",
    color: "pink",
    controls: "Click colored buttons",
  },
  {
    id: "crossyroad",
    name: "Crossy Road",
    icon: "🐔",
    description: "Hop forward infinitely across roads and rivers!",
    color: "yellow",
    controls: "Arrow keys / D-pad",
  },
  {
    id: "brickbreaker",
    name: "Brick Breaker",
    icon: "💎",
    description: "Break bricks with power-ups: wide paddle, multi-ball, laser!",
    color: "pink",
    controls: "Mouse / touch paddle",
  },
  {
    id: "tictactoe",
    name: "Tic-Tac-Toe",
    icon: "❌",
    description: "Outsmart the AI in the classic 3-in-a-row game!",
    color: "purple",
    controls: "Click a cell",
  },
  { id: "checkers", name: "Checkers", icon: "🔴", description: "Classic checkers vs AI. Kings, jumps, strategy!", color: "red", controls: "Click piece then destination" },
  { id: "chess", name: "Chess", icon: "♟️", description: "Full chess vs AI. Castling, en passant, checkmate!", color: "cyan", controls: "Click piece then destination" },
  { id: "sudoku", name: "Sudoku", icon: "🔢", description: "Fill the 9x9 grid — no repeats in row, column, or box!", color: "yellow", controls: "Click cell, type number" },
  { id: "solitaire", name: "Solitaire", icon: "🃏", description: "Klondike solitaire — move cards to the four foundations!", color: "green", controls: "Click to select & move cards" },
  { id: "mahjong", name: "Mahjong", icon: "🀄", description: "Match pairs of free tiles to clear the board!", color: "purple", controls: "Click matching tile pairs" },
  { id: "battleship", name: "Battleship", icon: "🚢", description: "Place ships, then blast the enemy fleet!", color: "cyan", controls: "Click to place/fire" },
  { id: "reversi", name: "Reversi", icon: "⚫", description: "Flip opponent discs to control the board!", color: "green", controls: "Click valid squares" },
  { id: "go", name: "Go", icon: "⬜", description: "Capture territory on the 9x9 Go board!", color: "pink", controls: "Click to place stone" },
  { id: "dominoes", name: "Dominoes", icon: "🁣", description: "Match domino chain ends against the AI!", color: "yellow", controls: "Click domino to play" },
  { id: "backgammon", name: "Backgammon", icon: "🎲", description: "Race your pieces home before the AI does!", color: "red", controls: "Click piece then point" },
  { id: "yahtzee", name: "Yahtzee", icon: "🎯", description: "Roll 5 dice and score all 13 categories!", color: "purple", controls: "Click dice to hold, click score" },
  { id: "blackjack", name: "Blackjack", icon: "🃏", description: "Beat the dealer — get closer to 21 without busting!", color: "green", controls: "Hit, Stand, Double Down" },
  { id: "videopoker", name: "Video Poker", icon: "🂡", description: "5-card draw Jacks or Better — hold your winners!", color: "yellow", controls: "Click cards to hold/discard" },
  { id: "wordsearch", name: "Word Search", icon: "🔍", description: "Find all hidden words in the letter grid!", color: "cyan", controls: "Click and drag to select" },
  { id: "hangman", name: "Hangman", icon: "🪢", description: "Guess the word before the man is hanged!", color: "pink", controls: "Click letters or type" },
  { id: "boggle", name: "Boggle", icon: "🔡", description: "Find words in the 4x4 grid before time runs out!", color: "purple", controls: "Click adjacent letters" },
  { id: "slidingpuzzle", name: "Sliding Puzzle", icon: "🧩", description: "Slide tiles to arrange them in order 1-15!", color: "cyan", controls: "Click tile adjacent to gap" },
  { id: "hanoi", name: "Towers of Hanoi", icon: "🗼", description: "Move all discs from left to right peg!", color: "yellow", controls: "Click peg to pick/place disc" },
  { id: "nonogram", name: "Nonogram", icon: "🖼️", description: "Solve the pixel art logic puzzle!", color: "green", controls: "Click to fill, right-click to mark X" },
  { id: "lightsout", name: "Lights Out", icon: "💡", description: "Toggle adjacent lights to turn them all off!", color: "yellow", controls: "Click lights to toggle" },
  { id: "mancala", name: "Mancala", icon: "🪨", description: "Sow seeds and fill your store before the AI!", color: "red", controls: "Click your pit to sow" },
  { id: "morris", name: "Nine Men's Morris", icon: "⬛", description: "Form mills to capture opponent pieces!", color: "purple", controls: "Click to place/move piece" },
  { id: "hex", name: "Hex", icon: "🔷", description: "Connect your edges across the board!", color: "cyan", controls: "Click hexagon to place" },
  { id: "dotsboxes", name: "Dots & Boxes", icon: "📦", description: "Claim boxes by completing their sides!", color: "pink", controls: "Click edges between dots" },
  { id: "mastermind", name: "Mastermind", icon: "🎨", description: "Crack the secret 4-color code in 10 guesses!", color: "purple", controls: "Click colors then submit" },
  { id: "nim", name: "Nim", icon: "🪵", description: "Take objects strategically — don't take the last one!", color: "red", controls: "Click objects to remove" },
  { id: "cribbage", name: "Cribbage", icon: "🃏", description: "Build a hand, play cards, and count your points!", color: "green", controls: "Click to discard/play cards" },
  { id: "concentration", name: "Concentration", icon: "🧠", description: "Match all 20 pairs with combos and timer!", color: "pink", controls: "Click cards to flip" },
  { id: "connectfive", name: "Connect Five", icon: "🟡", description: "Get 5 in a row on the 15x15 board before the AI!", color: "yellow", controls: "Click to place stone" },
  { id: "samegame", name: "SameGame", icon: "🟦", description: "Remove groups of same-colored tiles to clear the board!", color: "cyan", controls: "Click a group to remove" },
];

export type GameScreen = "lobby" | "game";
